const products = [
    {
      id: 1,
      name: "Sándwich Clásico de Jamón y Queso",
      category: "clasicos",
      description: "Clásico sándwich de miga triple relleno de jamón cocido y queso.",
      price: 1857,
      stock: 10,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/Jamon-Cocido-y-queso-768x1024.jpg",
    },
    {
      id: 2,
      name: "Sándwich de Miga Triple Crudo y Queso",
      category: "premium",
      description: "Delicioso sándwich de miga triple con jamón crudo y queso.",
      price: 2285.75,
      stock: 8,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/Crudo-y-queso-768x1024.jpg",
    },
    {
      id: 3,
      name: "Sándwich de Miga Triple Jamón y Huevo",
      category: "clasicos",
      description: "Sándwich de miga triple relleno de jamón cocido y huevo duro.",
      price: 2000,
      stock: 15,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/d70a1b10e302586782fe2ac9887fa84fo-800x800.jpg",
    },
    {
      id: 4,
      name: "Sándwich de Miga Triple Jamón y Roquefort",
      category: "especial",
      description: "Exquisito sándwich de miga triple con jamón cocido y queso roquefort.",
      price: 2143,
      stock: 12,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/Jamon-y-Roquefort-800x800.jpg",
    },
    {
      id: 5,
      name: "Sándwich de Miga Triple Capresse",
      category: "clasicos",
      description: "Fresco sándwich de miga triple con tomate, albahaca y queso mozzarella.",
      price: 2000,
      stock: 10,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/3901303854d4848388d00e2276ad5b1ao-scaled.jpg",
    },
    {
      id: 6,
      name: "Sándwich de Miga Triple Jamón y Tomates",
      category: "tradicional",
      description: "Sándwich de miga triple con jamón cocido y rodajas de tomate fresco.",
      price: 2000,
      stock: 8,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/Jamon-y-tomate-800x800.jpg",
    },
    {
      id: 7,
      name: "Sándwich de Miga Triple Pastrón y Pepinillos",
      category: "premium",
      description: "Sándwich de miga triple con pastrón y rodajas de pepinillos en vinagre.",
      price: 2285.75,
      stock: 5,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/4474e457-e11c-44c7-9e9e-7252a7423e5c-800x800.jpg",
    },
    {
      id: 8,
      name: "Sándwich de Miga Triple Atún y Queso",
      category: "clasicos",
      description: "Sándwich de miga triple relleno de atún y queso.",
      price: 10286,
      stock: 4,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/d80b4759-cebe-498c-adea-a1f12261b2ca-800x800.jpg",
    },
    {
      id: 9,
      name: "Sándwich de Miga Triple Queso y Huevo",
      category: "tradicional",
      description: "Sándwich de miga triple con queso y huevo duro.",
      price: 2000,
      stock: 10,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/Queso-y-huevo-800x800.jpg",
    },
    {
      id: 10,
      name: "Sándwich de Miga Triple Salame y Queso",
      category: "especial",
      description: "Sándwich de miga triple con salame y queso.",
      price: 2143,
      stock: 6,
      image: "https://ramalloclub.com/wp-content/uploads/2021/03/16d00c045e1b95c97c5db3ba467cce49o-800x800.jpg",
    },
  ];
  
  export default products;
  
  